# The Shareabouts API dataset username & name used by this map.
# You MUST change this after creating a dataset.
api_root: http://saapi-mboos.dotcloud.com/api/v1/datasets/
dataset: mboos/kitchbike

# And the associated API key.
dataset_api_key: 

# Settings for the app
app:
  # HTML Title
  title: Kitchener Bikes (Beta)
  # Header name
  name: Kitchener Bikes (Beta)
  # Meta description that will show up in Google search results
  meta_description: Use the Kitchener Bikes Shareabouts tool to recommend cycling areas, suggest bicycle parking locations and bike lanes, and report safety issues.

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: 43.430
      lng: -80.476
    zoom: 14
    minZoom: 11
    maxZoom: 17
  base_layer:
    url: http://tilestream-mboos.dotcloud.com/v2/KitchenerBike/{z}/{x}/{y}.png
    #url: http://{s}.tiles.mapbox.com/v3/mapbox.mapbox-streets/{z}/{x}/{y}.png
    attribution: '&copy; <a href="http://www.openstreetmap.org" target="_blank">OpenStreetMap contributors, ODbL.</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Landmark:
    default: blue
    focused: red
  Park:
    default: blue
    focused: red
  School:
    default: blue
    focused: red
  Suggest bike parking:
    default: blue
    focused: post
  Hazardous for biking:
    default: reddot
    focused: hazard
  Suggest bike infrastructure:
    default: blue
    focused: suggest
  Great for biking:
    default: greendot
    focused: heart

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  reddot:
    iconUrl: /static/css/images/reddot.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  greendot:
    iconUrl: /static/css/images/greendot.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  hazard:
    iconUrl: /static/css/images/hazard.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  post:
    iconUrl: /static/css/images/post.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  suggest:
    iconUrl: /static/css/images/suggest.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  heart:
    iconUrl: /static/css/images/heart.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 5000

place:
  adding_supported: true
  add_button_label: Mark a Place
  action_text: added
  title: Tell us more...
  action_text: added
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Brief Description
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Brief Description
        - key: size
          value: 30
    - prompt: Feedback Type
      type: select
      options:
        - Great for biking
        - Hazardous for biking
        - Suggest bike parking
        - Suggest bike infrastructure
      name: location_type
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30
#    - prompt: Your Email
#      type: text
#      name: submitter_email
#      optional: true
#      attrs:
#        - key: placeholder
#          value: Email
#        - key: size
#          value: 30
    - prompt: Detailed Description
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: Description...

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      label: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    url: /static/pages/overview.html
    start_page: true

  - title: "Why Shareabouts?"
    slug: why
    url: /static/pages/why.html

  - title: Features
    slug: features
    url: /static/pages/features.html

  - title: OpenPlans
    external: true
    url: http://www.openplans.org
